openapi: 3.0.0
info:
  title: SinaDLabs Audio Transcription API
  description: API for transcribing audio files using SinaDLabs
  version: 1.0.0
servers:
  - url: https://api.sinadlabs.com/v1
paths:
  /audio/transcriptions:
    post:
      summary: Transcribe Audio File
      description: Transcribes the provided audio file
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: uri
                  description: The URL of the audio file to be transcribed
                language:
                  type: string
                  description: The language of the audio content
              required:
                - file
                - language
      responses:
        '200':
          description: Successful transcription
          content:
            application/json:
              schema:
                type: object
                properties:
                  transcription:
                    type: string
                    description: The transcription of the audio file
      security:
        - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
